config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :questions, except: [:show, :new, :index]
  resources :hashtags, only: [:show], param: :name

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_and_belongs_to_many :questions

  validates :name, presence: true, uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_and_belongs_to_many :hashtags

  validates :text, :user, presence: true
  validates :text, length: { maximum: 255 }

  before_save :find_hashtags

  def find_hashtags
    self.hashtags = "#{text} #{answer}".scan(/#[a-zA-Zа-яА-Я0-9_-]+/).
      map { |word| word.downcase }.uniq.
      map { |word| Hashtag.find_or_create_by(name: word) }
  end
end

app/models/user.rb
require 'uri'
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  before_validation :username_in_lowercase

  validates :email, :username, presence: true
  validates :email, :username, uniqueness: true
  validates :email, format: { with: /@/ } # для типа "админ@почта.рф"

  validates :username,
            length: { maximum: 40 },
            format: { with: /\A[\w]+\z/ }

  validates :background_color,
            allow_blank: true,
            format: { with: /\A\#([a-fA-F]|[0-9]){3,6}\z/ }

  attr_accessor :password
  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  before_save :encrypt_password

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password

    nil
  end

  def username_in_lowercase
    self.username = username&.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find_by(name: params[:name])

    if @hashtag
      @questions = @hashtag.questions.order(created_at: :desc)
    else
      redirect_to root_url, notice: 'хештегов ен найдено'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:edit, :update, :destroy]

  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user

    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос удален :('
  end

  private
  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? &&
      params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_url, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.joins(:questions).order(:name).uniq
  end

  def new
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new
  end

  def create
    redirect_to root_url, alert: 'Вы уже залогинены' if current_user.present?

    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Ваш аккаунт успешно удален.'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end

  private
  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email,
                                 :password,
                                 :password_confirmation,
                                 :name,
                                 :username,
                                 :avatar_url,
                                 :background_color
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def declension(quantity, one, few, many)
    return many if (quantity % 100).between?(11, 14)

    case quantity % 10
    when 1 then one
    when 2..4 then few
    else many
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

  def background_setting(user)
    "#005a55" unless user.background_color?
  end

  def hashtag_to_link(text)
    text.gsub(/#[a-zA-Zа-яА-Я0-9_-]+/) do |word|
      link_to word, hashtag_url(word.downcase)
    end
  end
end

app/views/hashtags/_hashtag.html.erb
<% @hashtags.each do |word| %>
  <%= link_to word.name, hashtag_url(word.name), class: 'tag' %>
<% end %>

app/views/hashtags/show.html.erb
<div class="user-questions buffer-both">
  <div class="questions-list">
    <%= render partial: 'questions/question', collection: @questions %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Хорошие вопросы</title>
  <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: { method: :delete } %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path,
                    class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
                    class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <%= recaptcha_tags unless current_user.present? %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="">
      <% if question.author %>
        <%= link_to "От #{question.author.name}", user_path(question.author) %>
      <% else %>
        <%= 'автор не представился' %>
      <% end %>
    </div>

    <div class="question-text text-lead">
      <%= hashtag_to_link(question.text).html_safe %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= hashtag_to_link(question.answer).html_safe %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет фона блока с аватаркой', class: 'form-label' %>
        <%= f.color_field :background_color, value: background_setting(@user) %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <div class="buffer-top-large">
      <%= link_to "Удалить аккаунт", @user, method: :delete, data: {confirm: 'Ваш аккаунт будет удалён!'} if current_user == @user %>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>

  <div class="buffer-both">
    <h1 class="title-medium">Наши хештеги</h1>
    <%= render 'hashtags/hashtag' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center"
     style="background: <%= @user.background_color %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: 'Фото' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="question-content text-center pointer-cursor hide">
      <%= "У пользователя" %>
      <%= @user.name %>
      <%= "всего" %>
      <div class="user-statistics container">
        <div class="column-1-3">
          <h1 class="title-small"><%= @questions_count %></h1>
          <p><%= declension(@questions_count, "вопрос", "вопроса", "вопросов") %></p>
        </div>
        <div class="column-1-3">
          <h1 class="title-small"><%= @answers_count %></h1>
          <p><%= declension(@answers_count, "ответ", "ответа", "ответов") %></p>
        </div>
        <div class="column-1-3">
          <h1 class="title-small"><%= @unanswered_count %></h1>
          <p><%= declension(@unanswered_count, "безответный вопрос", "безответных вопроса", "безответных вопросов") %></p>
        </div>
      </div>
    </div>

    <div class="questions-list show">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>